mnBackup
========

Утилита бэкапа на .net. Без клиент-серверной технологии для небольших бэкапов

Альфа версия, не тестировалась!!!

Распространяется по лицензии http://www.gnu.org/licenses/gpl-3.0.html[GNU GPL 3]

[red]#ВАЖНО!!! ВЫ ИСПОЛЬЗУЕТЕ ДАННЫЙ ПРОГРАММНЫЙ ПРОДУКТ НА СВОЙ СТРАХ И РИСК!!!#

*Автор заранее слагает с себя ответственность за весь возможный ущерб, причиненный программой.*


Описание работы
---------------

Программа предназначена для бэкапа с небольшого количества компьютеров. Т.к. на больше лучше использовать клиент-серверные технологии.
Архивирует в 7zip, возможно разбиение на тома в случае большого количества данных. Возможно указание пароля на архивы (пароль хранится в открытом виде).
Возможно разностное копирование и удаление архивов старше заданого интервала.
Задачи можно описывать через командную строку или через файл формата json. Графический интерфейс отсутствует.
Встроенного планировщика нет, подразумевается использование стороннего.

Теневое копирование
~~~~~~~~~~~~~~~~~~~

Возможно использование теневого копирования для бэкапа открытых файлов. Для теневого копирования необходимы права администратора и запуск на том копьютере, где находится копируемый диск (теневое копирование по сети не работает). В случае использования теневого копирования, в каталогах источниках можно указывать только один диск. Т.к. копия будет создана только для одного диска.

Временный каталог
~~~~~~~~~~~~~~~~~

Можно указывать несколько каталогов приемников архивов, для большей сохранности копий. Если каталогов несколько, используется архивация во временный каталог, затем копирование архивов по каталогам назначения.
Общий принцип использования временного каталога:

* если временный каталог (TempDir) не задан в настройках или через командную строку, то архивация идет в первый каталог приемника, далее оттуда архивы копируются в остальные приемники (если они есть)
* если первый каталог приемника находится на локальном фиксированном диске, то архивация идет сразу в первый каталог приемника, а оттуда копируется далее. Не важно, задан ли в этом случае архивный каталог или нет.
* если каталог применика сетевой, съемный и т.п. и архивный каталог задан, то архивация идет сначала в архивный кататалог, а потом уже копируется в приемник (даже если он один)

 
Настройки
---------

Используемые настройки по умолчанию можно изменить в файле mnBackup.config (Формат xml)

Настройки командной строки с аналогичным именем перекроют общие настройки из файла.

ExposeVolume::
	Свободный диск в системе на который будет назначена теневая копия. По умолчанию берется
	первый свободный диск в системе.

Interval::
	Период между полными бэкапами если тип копирования не полный.
	Можно указывать число в днях или добавлять в конце наименование отрезка
	d, day - день
	w, week - неделя
	m, month - месяц
	y, year - год
	Например: 10d - 10 дней, 15 - 15 дней, 2m - 2 месяца, 1w - одна неделя,	month - 1 месяц
	По умолчанию 1 неделя.
Store::
	Время хранения полных бэкапов. 0 - ничего не удалять, по умолчанию.
	Время в днях, неделях, месяцах. Задается так же как интервал. Например 1m, 6m.
    
TaskFile::
	Файл заданий по умолчанию для команды run. По умолчанию "mnBackup.json"
	
TempDir::
	Временный каталог для создания архивов. Используется, если каталоги приемники находятся
	на сетевых дисках. По умолчанию не задан.

Prefix::
	Префикс по умолчанию, добавляющийся к имени задания в имени архива. Можно использовать подстановочные переменные: дата/время, переменные среды, имя компьютера/пользователя.
	По умолчанию: "_[yyMMdd-HHmmss]_{Type}".
	Итоговое имя архива: Имя задания + префикс.
 
Логи
----

Используется NLog. Настройки логов можно поменять в NLog.config согласно https://github.com/nlog/nlog/wiki[документации].
 
 
Параметры командной строки
--------------------------

Базовые команды

task::
	Выполнить задачу из командной строки
run::
	Выполнить задачи из файла
save::
	Записать задачу описанную в командной строке в файл
	
Параметры задачи (task)
~~~~~~~~~~~~~~~~~~~~~~~

s, source::
	Обязательный. Каталоги источники, разделенные точкой с запятой ";"

d, dest::
	Обязательный. Каталоги приемники арихвов, разделенные точкой с запятой ";"

name::
	Имя задания. Если не задано, используется имя последнего каталога первого источника

prefix::
	Префикс добавляющийся к имени задания в имени архива. Можно использовать подстановочные переменные: дата/время, переменные среды, имя компьютера/пользователя.
	По умолчанию: "_{yyMMdd-HHmmss}_[Type]".
	Итоговое имя архива: Имя задания + префикс.
	
t, type::
	Тип бэкапа: Full или Differential. По умолчанию Full.
	
interval::
	Период между полными бэкапами если тип копирования не полный.
	Можно указывать число в днях или добавлять в конце наименование отрезка
	d, day - день
	w, week - неделя
	m, month - месяц
	y, year - год
	Например: 10d - 10 дней, 15 - 15 дней, 2m - 2 месяца, 1w - одна неделя,	month - 1 месяц
	По умолчанию 1 месяц, умолчание можно изменить в файле настройки.
	
store::
	Время хранения полных бэкапов. 0 - ничего не удалять
	Время в днях, неделях, месяцах. Задается так же как интервал. Например 1m, 6m.
	
v, VolumeSize::
	Разделить архивы на тома с заданным размером в байтах. По умолчанию не разделять (0).
	
shadow::
	Использовать теневое копирование. По умолчанию отключено.
	При использовании данной опции каталоги источники должны находится на одном диске.
	Теневая копия назначается на первый свободный диск в системе. Свой диск можно задать
	параметром ExposeVolume.
	
i, include::
	Маски файлов включаемых в фильтр. Маски разделяются точкой с запятой ";"
	
e, exclude::
	Маски файлов исключаемых из фильтра. Маски разделяются точкой с запятой ";"

older::
	Архивировать файлы старее чем.
	
newer::
	Архивировать файлы новее чем.

Примеры

-----------
mnbackup task -s d:\temp -d d:\arh
-----------
Архивация каталога temp в arh. Полная копия, архивы хранятся постоянно, если не сменили настройки.

-----------
mnbackup task -s d:\temp -d d:\arh --shadow
-----------
Архивация каталога temp в arh используя теневое копирование

-----------
mnbackup task -s d:\temp -d d:\arh -t Differential --interval week --store 3m
-----------
Архивация каталога temp в arh. Полная копия создается раз в неделю, полные копии хранятся 3 месяца, после чего удаляются.

-----------
mnbackup task -s c:\Users;c:\Data -d \\server1\store;\\server2\store --TempDir d:\temp --shadow
-----------
Архивация каталогов Users и Data на сервера server1 и server2 используя временный каталог d:\temp и теневое копирование.
	
Параметры запуска (run)
~~~~~~~~~~~~~~~~~~~~~~~

f, file::
	Имя файла с задачами. Если не укзан, берется из настроек. По умолчанию  "mnBackup.json".

Параметры сохранения (save)
~~~~~~~~~~~~~~~~~~~~~~~~~~~

Позволяет сохранить задачу описанную в командной строке в файл. К описанию задачи добавьте имя файла в который вы хотите сохранить задачу.
Например

-----------
mnbackup save -f Users.json -s c:\Users -d \\server1\store;\\server2\store --shadow
-----------

Записать задачу в файл Users.json.

Далее можно запускать

-----------
mnbackup run -f Users.json --TempDir d:\temp
-----------

	
Общие параметры
~~~~~~~~~~~~~~~

ExposeVolume::
	Свободный диск в системе на который будет назначена теневая копия. По умолчанию берется
	первый свободный диск в системе.
 
TempDir::
	Временный каталог для создания архивов. Используется, если каталоги приемники находятся
	на сетевых дисках.

Переменные для префикса
-----------------------

В имени префикса (prefix) можно использовать переменные даты/времени, типа копирования и т.п. Имя архива будет складываться из имени задания + префикс.
Переменные даты/времени нужно обрамлять в квадратные скобки [].
Переменные среды обрамляются в проценты %%.




	
Используются проекты
--------------------

 * http://nlog-project.org/[Nlog] - Логи
 * https://commandline.codeplex.com/[libcmdline] - Разбор командной строки
 * http://alphavss.codeplex.com/[AlphaVSS] - Теневое копирования
 * http://sevenzipsharp.codeplex.com/[SevenZipSharp] - архивация 7zip, немного исправлен
 * http://www.nunit.org/[NUnit] - Тесты
 
 